/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products/route'
import { Route as CategoriesRouteImport } from './routes/categories/route'
import { Route as ProductsNewRouteImport } from './routes/products/new/route'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId/route'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ProductsIndexLazyImport = createFileRoute('/products/')()

// Create/Update Routes

const ProductsRouteRoute = ProductsRouteImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products/route.lazy').then((d) => d.Route),
)

const CategoriesRouteRoute = CategoriesRouteImport.update({
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/categories/route.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProductsIndexLazyRoute = ProductsIndexLazyImport.update({
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any).lazy(() =>
  import('./routes/products/index.lazy').then((d) => d.Route),
)

const ProductsNewRouteRoute = ProductsNewRouteImport.update({
  path: '/new',
  getParentRoute: () => ProductsRouteRoute,
} as any).lazy(() =>
  import('./routes/products/new/route.lazy').then((d) => d.Route),
)

const ProductsProductIdRouteRoute = ProductsProductIdRouteImport.update({
  path: '/$productId',
  getParentRoute: () => ProductsRouteRoute,
} as any).lazy(() =>
  import('./routes/products/$productId/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexLazyImport
      parentRoute: typeof ProductsRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CategoriesRouteRoute,
  ProductsRouteRoute: ProductsRouteRoute.addChildren({
    ProductsProductIdRouteRoute,
    ProductsNewRouteRoute,
    ProductsIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/categories",
        "/products"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/categories": {
      "filePath": "categories/route.tsx"
    },
    "/products": {
      "filePath": "products/route.tsx",
      "children": [
        "/products/$productId",
        "/products/new",
        "/products/"
      ]
    },
    "/products/$productId": {
      "filePath": "products/$productId/route.tsx",
      "parent": "/products"
    },
    "/products/new": {
      "filePath": "products/new/route.tsx",
      "parent": "/products"
    },
    "/products/": {
      "filePath": "products/index.lazy.tsx",
      "parent": "/products"
    }
  }
}
ROUTE_MANIFEST_END */
